(defun c:ExportText (/ ss i file text)
  (setq ss (ssget "_X" '((0 . "TEXT,MTEXT"))))
  (setq i 0)
  (setq file (open "C:/Path/To/Save/Text.txt" "w"))
  (while (< i (sslength ss))
    (setq text (cdr (assoc 1 (entget (ssname ss i)))))
    (write-line text file)
    (setq i (1+ i))
  )
  (close file)
  (princ "Text Exported Successfully.")
  (princ)
)
